# SHR-DAW controller profile v9
input=Arturia MiniLab mkII:Arturia MiniLab mkII MIDI 1
profile=arturia-minilab-mkii
menu.layout=8
encoder.relative_cc=112
encoder.relative_reverse=false
encoder.modified_relative_cc=7
encoder.modified_relative_reverse=false
encoder.press_cc=113
encoder.press_note=
encoder.press_channel=10
synth.press_cc=115
synth.press_note=
synth.press_channel=10
encoder.secondary_press_cc=115
encoder.secondary_press_note=
encoder.secondary_press_channel=10
encoder.modifier=
page_cycle.modifier=
page_cycle.trigger=
lock.cc=
rotary.2=74
rotary.3=71
rotary.4=76
rotary.5=77
rotary.6=93
rotary.7=73
rotary.8=75
rotary.9=114
rotary.10=18
rotary.11=19
rotary.12=16
rotary.13=17
rotary.14=91
rotary.15=79
rotary.16=72
pad.1=note.10.36
pad.2=note.10.37
pad.3=note.10.38
pad.4=note.10.39
pad.5=note.10.40
pad.6=note.10.41
pad.7=note.10.42
pad.8=note.10.43
